Update Ride Route
ACM-VIT/carpoolit-backend pull request #10
Opened 2023-12-18 20:19 UTC by harshitaak07

2023-12-19 05:41 UTC, harshitaak07 commented
Update Ride updates the ride according to id of ride, not the id of host user.

2023-12-19 06:50 UTC, RohanKhatua requested changes
Please see review comments.

2023-12-19 06:50 UTC, RohanKhatua commented on routes/rides/UpdateRide.go
> +type Ride struct {
Ride is already defined in models, why is it redefined here?

2023-12-19 06:50 UTC, RohanKhatua commented on routes/rides/UpdateRide.go
> +func CreateResponseRide(rideModel models.Ride, user models.User) Ride {
Why is a response ride being created?

2023-12-19 06:50 UTC, RohanKhatua commented on routes/rides/UpdateRide.go
> +func FindRide(id uint, ride *models.Ride) error {
Single DB function, does not need to be abstracted into another function.

2023-12-19 06:50 UTC, RohanKhatua commented on routes/rides/UpdateRide.go
> +	id, err := c.ParamsInt("id")
ID must be checked with strconv and atoi for only numbers

2023-12-19 06:50 UTC, RohanKhatua commented on routes/rides/UpdateRide.go
> +	if err := helpers.ValidateRide(modelsRide); err != nil {
Why is the ride validated after it has already been sent to the DB?

2023-12-19 06:50 UTC, RohanKhatua commented on routes/rides/UpdateRide.go
> +func ConvertToModelsRide(localRide Ride) models.Ride {
Again, unnecessary to just re-set every field.

2023-12-19 06:56 UTC, harshitaak07 commented on routes/rides/UpdateRide.go
> +type Ride struct {
okk wait I will call original

2023-12-19 06:57 UTC, harshitaak07 commented
I will make all the changes and send soon.

2023-12-19 06:59 UTC, harshitaak07 commented on routes/rides/UpdateRide.go
> +func CreateResponseRide(rideModel models.Ride, user models.User) Ride {
I did that because I created new Ride struct in this file. It is to effect the response structure to make . It maps models.Ride and models.User into Ride.

2023-12-19 07:00 UTC, harshitaak07 commented on routes/rides/UpdateRide.go
> +func FindRide(id uint, ride *models.Ride) error {
okk I will change this.

2023-12-19 07:01 UTC, harshitaak07 commented on routes/rides/UpdateRide.go
> +	if err := helpers.ValidateRide(modelsRide); err != nil {
Ok so I will validate before sending to DB

2023-12-19 07:01 UTC, harshitaak07 commented on routes/rides/UpdateRide.go
> +	id, err := c.ParamsInt("id")
ok noted

2023-12-19 08:09 UTC, harshitaak07 commented
made the required changes

2023-12-19 08:41 UTC, RohanKhatua requested changes
Please see review comments

2023-12-19 08:41 UTC, RohanKhatua commented on routes/rides/UpdateRide.go
> +	type UpdateRide struct { // struct for ride update
There is no need to create a new type and struct here, if all the data in the json passed to this route is valid and correct, just save that to the db, why create another struct?

2023-12-19 08:50 UTC, harshitaak07 commented on routes/rides/UpdateRide.go
> +	type UpdateRide struct { // struct for ride update
ohkkk let me fix

2023-12-19 09:36 UTC, harshitaak07 commented
made the changes: removed the UpdateRide struct

2023-12-19 10:46 UTC, RohanKhatua requested changes

2023-12-19 10:46 UTC, RohanKhatua commented on routes/rides/UpdateRide.go
> +	if err := c.BodyParser(&ride); err != nil {
The route should only take a JSON body or a parameter, not both. For an update, there should only be the JSON body. The ride ID can be found from the JSON itself.

2023-12-19 10:46 UTC, RohanKhatua commented on routes/rides/UpdateRide.go
>  	updatedRide := database.Database.Db.Save(&ride)
A save operation does not returrn a ride, it returns a *gorm.DB object, ideally name this `result`

2023-12-20 06:45 UTC, RohanKhatua approved these changes
LGTM

2023-12-20 06:50 UTC, RohanKhatua commented
closes #3

2023-12-20 06:51 UTC, merged