Created API route for creating a ride
ACM-VIT/carpoolit-backend pull request #11
Opened 2023-12-19 00:51 UTC by TrojanHorse0918

Issues fixed in this PR: #2 

API Endpoint: `/api/team/create`
Methods allowed: `POST`

### Request Sample:
`http://localhost:3000/createUser### ](http://127.0.0.1:3000/createRide`

Request Body:
```
{
    "host_user_id": 5,
    "start_location": "Mumbai",
    "end_location": "Pune",
    "start_time": "2024-12-31T23:00:00Z",
    "total_seats": 5,
    "booked_seats": 2,
    "total_price": 1000
}
```

### Response Sample:
```
{
    "ID": 0,
    "CreatedAt": "2023-12-19T06:15:23.3963644+05:30",
    "UpdatedAt": "2023-12-19T06:15:23.3963644+05:30",
    "DeletedAt": null,
    "id": 6,
    "host_user_id": 5,
    "host_user": {
        "ID": 0,
        "CreatedAt": "2023-12-19T06:14:44.920814+05:30",
        "UpdatedAt": "2023-12-19T06:14:44.920814+05:30",
        "DeletedAt": null,
        "id": 5,
        "name": "Manan Shah",
        "email": "manan04efbfgshah@gmail.com",
        "profile_picture_url": "https://www.google.com"
    },
    "start_location": "Mumbai",
    "end_location": "Pune",
    "start_time": "2024-12-31T23:00:00Z",
    "total_seats": 5,
    "booked_seats": 2,
    "total_price": 1000
}
```

###Error Cases

If using any other method except `POST`
Status: 400
```
{
    message: "Request method is not POST"
}
```

If there is an error parsing the JSON
Status: 400
```
{
    message: "Error parsing JSON"
}
```

If the request body isn't correctly formatted as per the ride model
Status: 400
```
{
    message: "Error validating ride"
}
```

If the host user does not exist
Status: 400
```
{
    message: "Host user does not exist"
}
```

If the start time of the ride is before current time
Status: 400
```
{
    message: "Start time is in the past"
}
```

If the total number of seats in the ride is lesser than the number of seats booked
Status: 400
```
{
    message: "Total seats available is less than booked seats"
}
```

Internal error
Status: 502
```
{
    message: "Error creating ride"
}
```

2023-12-19 06:44 UTC, RohanKhatua requested changes
Please check review comments

2023-12-19 06:44 UTC, RohanKhatua commented on routes/ride/createRide.go
> +	var hostUser []models.User
why is this an array?

2023-12-19 06:44 UTC, RohanKhatua commented on routes/ride/createRide.go
> +	result := database.Database.Db.Where("id = ?", ride.HostUserID).Find(&hostUser)
Host IDs are unique, just Db.First will most likely work

2023-12-19 06:44 UTC, RohanKhatua commented on routes/ride/createRide.go
> +	if len(hostUser) == 0 {
result := db.Find(&users)
if errors.Is(result.Error, gorm.ErrRecordNotFound) {
    // No records found
} else if result.Error != nil {
    // Some other error occurred
} else {
    // Records found
}

Better way to check if no records were found using Find

2023-12-19 06:44 UTC, RohanKhatua commented on routes/ride/createRide.go
> +	if ride.TotalSeats < ride.BookedSeats {
Should also disallow if booked seats = total seats, which implies car is full

2023-12-19 06:44 UTC, RohanKhatua commented on routes/ride/createRide.go
> +		return c.Status(502).SendString("Error creating ride")
Why 502? This is not necessarily a gateway issue.

2023-12-20 06:21 UTC, TrojanHorse0918 reviewed
The requested changes have been made, have used db.First() instead of db.Find() for user ID checking as db.Find() did not raise a gormError when no users were found.

2023-12-20 06:24 UTC, RohanKhatua requested changes

2023-12-20 06:24 UTC, RohanKhatua commented on routes/ride/createRide.go
>  	if c.Method() != "POST" {
Why check this? It is going to be registered as a POST route only.

2023-12-20 06:24 UTC, RohanKhatua commented on routes/ride/createRide.go
> +	ride.HostUser = hostUser
That is an FKey Reference, and does not need to be set explicitly.

2023-12-20 15:36 UTC, RohanKhatua approved these changes

2023-12-20 15:37 UTC, RohanKhatua commented
merging for time

2023-12-20 15:37 UTC, merged