Added Accept Route
ACM-VIT/carpoolit-backend pull request #34
Opened 2024-01-13 12:01 UTC by tanushgolwala

The Accept Route for Booking Route has been created

2024-01-13 12:27 UTC, tanushgolwala commented
#19

2024-01-14 04:41 UTC, RohanKhatua requested changes
See review comments

2024-01-14 04:41 UTC, RohanKhatua commented on models/UserModel.go
> +	RidesID           pq.Int64Array `gorm:"type:integer[]" json:"ride_ids"`
Why does the user need to have an array of ride IDs in the user table, why can they just not be referenced from the user id fkey relation present in the rides table?

2024-01-14 04:41 UTC, RohanKhatua commented on routes/bookings/AcceptRoute.go
> +	if err := database.Database.Db.First(&booking, bookingID).Error; err != nil {
Multiple DB operations part of a single API call should be part of a transaction.

2024-01-14 04:41 UTC, RohanKhatua commented on routes/bookings/AcceptRoute.go
> +	var User models.User
Again, this does not need to be done, if the relation is accessed via the fkey constraint

2024-01-14 16:25 UTC, RohanKhatua requested changes

2024-01-14 16:25 UTC, RohanKhatua commented on routes/users/getUserRides.go
> +	CreatedAt     string `json:"CreatedAt"`
Do not return CreatedAt and UpdatedAt in api response - unnecessary

2024-01-14 16:25 UTC, RohanKhatua commented on routes/users/getUserRides.go
> +	}
Just do a join.

2024-01-14 16:25 UTC, RohanKhatua commented on routes/bookings/AcceptRoute.go
> +	if err := database.Database.Db.First(&booking, bookingID).Error; err != nil {
don't see a tx yet

2024-01-15 11:05 UTC, RohanKhatua approved these changes
LGTM

2024-01-15 11:06 UTC, merged