feat: Delete User Route Added
ACM-VIT/carpoolit-backend pull request #37
Opened 2024-01-13 12:41 UTC by manan04shah

2024-01-14 04:46 UTC, RohanKhatua requested changes
see review comms

2024-01-14 04:46 UTC, RohanKhatua commented on routes/users/deleteUser.go
> +	if c.Method() != "DELETE" {
The route is registered as a delete route, all other http methods will automatically get rejected.

2024-01-14 04:46 UTC, RohanKhatua commented on routes/users/deleteUser.go
> +	if result.RowsAffected == 0 {
preferably, keep RowsAffected Check before err != nil, gorm quirks

2024-01-15 10:59 UTC, manan04shah commented
changes have been made

2024-01-15 11:07 UTC, RohanKhatua approved these changes
LGTM

2024-01-15 11:08 UTC, merged