Delete Booking Route
ACM-VIT/carpoolit-backend pull request #9
Opened 2023-12-18 20:12 UTC by gekyxme

2023-12-19 06:54 UTC, RohanKhatua requested changes
Please see review comments

2023-12-19 06:54 UTC, RohanKhatua commented on routes/bookings/deleteBooking.go
> +	bookingId, err := c.ParamsInt("id")
check id using strconv and atoi

2023-12-19 07:18 UTC, gekyxme commented on routes/bookings/deleteBooking.go
> +	bookingId, err := c.ParamsInt("id")
Made the changes

2023-12-20 04:55 UTC, RohanKhatua approved these changes
LGTM

2023-12-20 04:55 UTC, merged